---
AWSTemplateFormatVersion: "2010-09-09"
Description: exploring the cloudformation
Resources: 
  ntiervpc: 
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/16
      Tags:
        - Key: Name
          Value: ntier
  web1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-west-2b
      VpcId:
        Ref: ntiervpc
      CidrBlock: 192.168.0.0/24
      Tags:
       - Key: Name
         Value: web-1
  app1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-west-2b
      VpcId:
        Ref: ntiervpc
      CidrBlock: 192.168.1.0/24
      Tags:
       - Key: Name
         Value: app-1              
  web2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-west-2b
      VpcId:
        Ref: ntiervpc
      CidrBlock: 192.168.2.0/24
      Tags:
       - Key: Name
         Value: web-2    
  
  app2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-west-2b
      VpcId:
        Ref: ntiervpc
      CidrBlock: 192.168.3.0/24
      Tags:
       - Key: Name
         Value: app-2    
  db1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-west-2b
      VpcId:
        Ref: ntiervpc
      CidrBlock: 192.168.4.0/24
      Tags:
       - Key: Name
         Value: db-1 
  db2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-west-2b
      VpcId:
        Ref: ntiervpc
      CidrBlock: 192.168.5.0/24
      Tags:
       - Key: Name
         Value: db-2                     
